Update brew cask command
Brew has updated to only allow `brew install --cask`.

```sh
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```